# Generated by Django 2.2.3 on 2019-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='lists',
            field=models.TextField(default=''),
        ),
    ]
