# Generated by Django 2.2.3 on 2019-07-14 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20190715_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lists',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
